SELECT
  'CONVERTER' AS AREA,SUM(TRY_CAST([CONVERTER POWER(W)] AS FLOAT)) AS CONSUMED FROM CONVERTER UNION ALL
  SELECT
  'DETAILS',SUM(TRY_CAST([OPEN AREA POWER(W)] AS FLOAT)) AS Details FROM DETAILS UNION ALL
  SELECT
  'ELECTRONICS LAB',SUM(TRY_CAST([ELECTRONICS LAB POWER(W)] AS FLOAT)) AS Electronicslab FROM ELECTRONICS_LAB UNION ALL
  SELECT
  'EXHAUST FAN',SUM(TRY_CAST([EXHAUST & FAN POWER(W)] AS FLOAT)) AS Exhaustfan FROM EXHAUST_FAN UNION ALL
  SELECT
  'FILTRATION',SUM(TRY_CAST([FILTRATION POWER(W)] AS FLOAT)) AS Filtration FROM FILTRATION UNION ALL
  SELECT
  'FILTER',SUM(TRY_CAST([FILTER POWER(W)] AS FLOAT)) AS Filter FROM FITTER UNION ALL
  SELECT
  'IOT LAB',SUM(TRY_CAST([IOT LAB POWER(W)] AS FLOAT)) AS Iotlab FROM IOT_LAB UNION ALL
  SELECT
  'MICROBIOLOGY LAB',SUM(TRY_CAST([MICROBIOLOGY LAB POWER(W)] AS FLOAT)) AS Microbiologylab FROM MICROBIOLOGY_LAB UNION ALL
  SELECT
  'MOTOR TEST LAB',SUM(TRY_CAST([MOTOR TEST POWER(W)] AS FLOAT)) AS Motortestlab FROM MOTORTESTLAB UNION ALL
  SELECT
  'RPDB & WPDB',SUM(TRY_CAST([RPDB & WPDB POWER(W)] AS FLOAT)) AS Rpdb_Wpdb FROM RPDB_WPDB UNION ALL
  SELECT
  'TTIC LAB',SUM(TRY_CAST([TTIC LAB POWER(W)] AS FLOAT)) AS Tticlab FROM TTIC_LAB UNION ALL
  SELECT
  'WORKSHOP LAB',SUM(TRY_CAST([WORKSHOP POWER(W)] AS FLOAT)) AS Workshoplab FROM WORKSHOP_LAB
WHERE DateTime between :StartDate and :EndDate