SELECT
    round(SUM(TRY_CAST([ELECTRONICS LAB POWER(W)] AS FLOAT))/1000,2) AS [Total_Consumed]
FROM ELECTRONICS_LAB
WHERE YEAR(DateTime) = :selectedYear
GROUP BY YEAR(DateTime)
ORDER BY YEAR(DateTime);